# encoding: utf-8
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  labels:
    app: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: me-west1-docker.pkg.dev/elaborate-night-429819-i9/payments/production
          env:
            - name: PORT
              value: "3001"
            - name: NOTIFICATIONS_HOST
              value: notifications
            - name: NOTIFICATIONS_PORT
              value: "3000"
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe
                  key: apiKey
          ports:
            - containerPort: 3001