apiVersion: v1
kind: Service
metadata:
  name: payments
  labels:
    app: payments
spec:
  ports:
    - name: "3001"
      port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: payments
  type: ClusterIP

