apiVersion: v1
kind: Service
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  ports:
    - name: "3000"
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: notifications
  type: ClusterIP

