# encoding: utf-8
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: me-west1-docker.pkg.dev/elaborate-night-429819-i9/auth/production
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: connectionString
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: jwtSecret
            - name: JWT_EXPIRATION
              value: '3600'
            - name: HTTP_PORT
              value: '3003'
            - name: TCP_PORT
              value: '3002'
          ports:
            - containerPort: 3002
            - containerPort: 3003