apiVersion: v1
kind: Service
metadata:
  name: auth-http
  labels:
    app: auth
spec:
  ports:
    - name: "http"
      port: 3003
      protocol: TCP
      targetPort: 3003
  selector:
    app: auth
  type: NodePort

