apiVersion: v1
kind: Service
metadata:
  name: auth-tcp
  labels:
    app: auth
spec:
  ports:
    - name: "tcp"
      port: 3002
      protocol: TCP
      targetPort: 3002
  selector:
    app: auth
  type: ClusterIP

